import datetime
date_time = datetime.datetime.now()
print(date_time)
print(date_time.strftime("%a"))
print(date_time.strftime("%A"))
print(date_time.strftime("%w"))
print(date_time.strftime("%d"))
print(date_time.strftime("%b"))
print(date_time.strftime("%B"))
print(date_time.strftime("%m"))
print(date_time.strftime("%y"))
print(date_time.strftime("%Y"))
print(date_time.strftime("%H"))
print(date_time.strftime("%I"))
print(date_time.strftime("%p"))
print(date_time.strftime("%C"))